[package]
name = "encrypter"
version = "0.1.0"
authors = ["pontakornth <pontakorn61@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.3.2"
aes-ctr = "0.3.0"
sha2 = "0.8.1"
clap = "2.33.0"